services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./apache-config.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - database

  database:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=dict"
      - "MYSQL_USER=admin"
      - "MYSQL_PASSWORD=password1234"
      - "MYSQL_ROOT_PASSWORD=password1234"
      - "MYSQL_RANDOM_ROOT_PASSWORD="

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - database
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password1234

volumes:
  db-data:
